name: sync_to_gitee
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'lan-tianxiang/clone_scripts'
    timeout-minutes: 500
    steps:
      - name: sync_to_gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/lan-tianxiang
          dst: gitee/highdimen
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          white_list: "jd_shell,jd_scripts"
          #black_list: "hashes"
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:lan-tianxiang/clone_scripts.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:highdimen/clone_scripts.git
