name: sync_to_gitee
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'lan-tianxiang/clone_scripts'
    timeout-minutes: 2
    steps:
      - name: sync_to_gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/lan-tianxiang
          dst: gitee/highdimen
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          white_list: "clone_scripts,jd_shell,jd_scripts"
          #black_list: "hashes"
